# Generated by Django 5.2.18 on 2026-10-08 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_word', models.PositiveIntegerField(default=2, verbose_name='pontos por palavra traduzida')),
                ('reviewed_word', models.PositiveIntegerField(default=1, verbose_name='pontos por palavra revisada')),
            ],
            options={
                'verbose_name': 'taxas de pontos',
                'verbose_name_plural': 'taxas de pontos',
            },
        ),
        migrations.CreateModel(
            name='UnclaimedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_username', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('translated', 'Tradução'), ('reviewed', 'Revisão'), ('redemption', 'Resgate'), ('refund', 'Estorno'), ('adjustment', 'Ajuste')], max_length=12)),
                ('string_key', models.CharField(max_length=500)),
                ('words', models.PositiveIntegerField()),
                ('amount', models.IntegerField()),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('string_key', 'kind'), name='unique_unclaimed_per_string')],
            },
        ),
        migrations.CreateModel(
            name='PointEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('kind', models.CharField(choices=[('translated', 'Tradução'), ('reviewed', 'Revisão'), ('redemption', 'Resgate'), ('refund', 'Estorno'), ('adjustment', 'Ajuste')], max_length=12)),
                ('string_key', models.CharField(blank=True, max_length=500)),
                ('words', models.PositiveIntegerField(default=0)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='point_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('string_key', ''), _negated=True), fields=('string_key', 'kind'), name='unique_progress_per_string')],
            },
        ),
    ]
