# Generated by Django 5.2.18 on 2026-10-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointentry',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'lançamento de pontos', 'verbose_name_plural': 'lançamentos de pontos'},
        ),
        migrations.AlterModelOptions(
            name='unclaimedevent',
            options={'verbose_name': 'evento pendente', 'verbose_name_plural': 'eventos pendentes'},
        ),
    ]
