# Generated by Django 5.2.18 on 2026-10-08 01:37

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transifex_username', models.CharField(blank=True, max_length=150, verbose_name='usuário no Transifex')),
                ('link_status', models.CharField(choices=[('none', 'Sem vínculo'), ('pending', 'Aguardando aprovação'), ('approved', 'Aprovado'), ('rejected', 'Recusado')], default='none', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('transifex_username'), condition=models.Q(('link_status', 'approved')), name='unique_approved_transifex_username')],
            },
        ),
    ]
