# Generated by Django 5.2.18 on 2026-10-08 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0002_alter_pointentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('cost', models.PositiveIntegerField(verbose_name='custo (pontos)')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='foto (URL)')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('allows_mail', models.BooleanField(default=True, verbose_name='envio pelos Correios')),
                ('allows_pickup', models.BooleanField(default=True, verbose_name='retirada em mãos')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix_instructions', models.TextField(blank=True, help_text="Vai no e-mail de aprovação de pedidos pelos Correios (chave Pix, valor ou 'a combinar').", verbose_name='instruções do Pix do frete')),
            ],
            options={
                'verbose_name': 'configurações da loja',
                'verbose_name_plural': 'configurações da loja',
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(verbose_name='custo pago (pontos)')),
                ('delivery', models.CharField(choices=[('mail', 'Correios'), ('pickup', 'Em mãos')], max_length=10, verbose_name='entrega')),
                ('status', models.CharField(choices=[('requested', 'Pedido'), ('approved', 'Aprovado'), ('shipping_paid', 'Frete pago'), ('shipped', 'Enviado'), ('ready_for_pickup', 'Pronto para retirar'), ('delivered', 'Entregue'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado')], default='requested', max_length=20, verbose_name='etapa')),
                ('request_token', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=120, verbose_name='nome completo')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='rua')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('tracking_code', models.CharField(blank=True, max_length=40, verbose_name='código de rastreio')),
                ('admin_note', models.TextField(blank=True, verbose_name='observação para o tradutor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='pedido em')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='entregue em')),
                ('address_erased_at', models.DateTimeField(blank=True, null=True, verbose_name='endereço apagado em')),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redemption', to='ledger.pointentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to=settings.AUTH_USER_MODEL, verbose_name='tradutor')),
            ],
            options={
                'verbose_name': 'resgate',
                'verbose_name_plural': 'resgates',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RedemptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(blank=True, max_length=20, verbose_name='de')),
                ('status_to', models.CharField(blank=True, max_length=20, verbose_name='para')),
                ('note', models.TextField(blank=True, verbose_name='observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='quando')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='por')),
                ('redemption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shop.redemption')),
            ],
            options={
                'verbose_name': 'evento do resgate',
                'verbose_name_plural': 'histórico',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='variação')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='estoque')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'variação',
                'verbose_name_plural': 'variações',
                'ordering': ['product', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='redemption',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='shop.variant', verbose_name='item'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_variant_name_per_product'),
        ),
    ]
