# Generated by Django 5.2.18 on 2026-10-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=300, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('cursor', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'recurso monitorado',
                'verbose_name_plural': 'recursos monitorados',
                'ordering': ['resource_id'],
            },
        ),
    ]
